/**
 * Character Configuration (AUTO-GENERATED)
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run: npm run generate:characters
 *
 * To add a new character:
 * 1. Create folder: public/assets/characters/{key}/
 * 2. Add spritesheet: public/assets/characters/{key}/{key}.png
 *    - 4x4 grid (16 frames), 192x192 pixels (48x48 per frame)
 *    - Row 0: Down, Row 1: Up, Row 2: Left, Row 3: Right
 * 3. Run: npm run generate:characters
 */

export interface CharacterDefinition {
    key: string;           // Unique key for the character (also folder/file name)
    displayName: string;   // Display name shown to user
    frameWidth: number;    // Width of each frame
    frameHeight: number;   // Height of each frame
}

/**
 * List of all available playable characters
 * Generated from: public/assets/characters/
 */
export const PLAYABLE_CHARACTERS: CharacterDefinition[] = [
    { key: 'bear', displayName: 'Bear', frameWidth: 48, frameHeight: 48 },
    { key: 'boy', displayName: 'Boy', frameWidth: 48, frameHeight: 48 },
    { key: 'lion', displayName: 'Lion', frameWidth: 48, frameHeight: 48 },
    { key: 'panda', displayName: 'Panda', frameWidth: 48, frameHeight: 48 },
    { key: 'rabit', displayName: 'Rabit', frameWidth: 48, frameHeight: 48 }
];

/**
 * Get character keys as readonly array
 */
export const CHARACTER_KEYS = PLAYABLE_CHARACTERS.map(c => c.key) as readonly string[];

/**
 * Default character key (first in list)
 */
export const DEFAULT_CHARACTER = PLAYABLE_CHARACTERS[0]?.key || 'lion';

/**
 * Get character definition by key
 */
export function getCharacterByKey(key: string): CharacterDefinition | undefined {
    return PLAYABLE_CHARACTERS.find(c => c.key === key);
}

/**
 * Get next character key (for cycling through characters)
 */
export function getNextCharacterKey(currentKey: string): string {
    const currentIndex = CHARACTER_KEYS.indexOf(currentKey);
    const nextIndex = (currentIndex + 1) % CHARACTER_KEYS.length;
    return CHARACTER_KEYS[nextIndex];
}
